### ISSUE TITLE
.net core 2.0

### ISSUE THREAD

**Issue by ghost** [imranmomin/Hangfire.AzureDocumentDB#11]
Hi, does this work on .net core 2.0?

Thanks

**Comment by pjbgf** [comment]
@brightertools it looks like it does not. I have created a pull request #12 to add that support.

**Comment by imranmomin** [comment]
@pjbgf I too had created the a branch to move the project under .net core / standard. I will put some time and check if it is same and some test.. Hopefully I will merge it soon
