### ISSUE TITLE
Automatic partitioning support

### ISSUE THREAD

**Issue by dominikfoldi** [imranmomin/Hangfire.AzureDocumentDB#26]
The library does not support partitioning.

Could you please add that into it?

**Comment by imranmomin** [comment]
@dominikfoldi Looking at the lifetime collection size, I don't think that will have any impact on the performance. Can you provide an use-case to have a partition?

**Comment by dominikfoldi** [comment]
It is not about performance but there can be problems arise if I use Hangfire with a partitioned collection. E.g. the recommended way to use Cosmos Db if you do not want to pay too much is to store every type of documents in one collection. You already do it for Hangfire entities by providing DocumentType property.

We have tried to use a library for Document DB before without partitioning with our partitioned collection and there where couple of problems because of it.

**Comment by imranmomin** [comment]
@dominikfoldi  Can you provide me the exception raised while using it on your partitioned collection 

Else you can create the collection with a partition key before calling the library. There is a check to create collection only if not exists 

```csharp
DocumentClient client = new DocumentClient(new Uri(endpoint), authKey);
await client.CreateDatabaseAsync(new Database { Id = "db" });

DocumentCollection myCollection = new DocumentCollection();
myCollection.Id = "jobs";
myCollection.PartitionKey.Paths.Add("/type");

await client.CreateDocumentCollectionAsync(UriFactory.CreateDatabaseUri("db"), myCollection, new RequestOptions { OfferThroughput = 20000 });
```

**Comment by dominikfoldi** [comment]
@imranmomin I have not tried it yet with partitioned nor non-partitioned collection, we are just looking for options how we can use Hangfire right now.

I was speaking from my experience with other libraries that did not support partitioning. I will examine this later in this year.
