### ISSUE TITLE
Use singleton DocumentClient

### ISSUE THREAD

**Issue by dominikfoldi** [imranmomin/Hangfire.AzureDocumentDB#27]
The library creates a DocumentClient, but the recommended way is to use only one DocumentClient as a singleton and inject it everywhere.

The library should inject it first and if it is null then create a new one and add it to the IoC container. Or provide a method to create the DocumentClient, add it to the IoC container and throw an exception if there is no DocumentClient created.

**Comment by imranmomin** [comment]
I think, I was initializing the `DocumentClient` only once. 
https://github.com/imranmomin/Hangfire.AzureDocumentDB/blob/4f76a043c7f3849a758cca21f808af1e352a41a3/Hangfire.AzureDocumentDB/DocumentDbStorage.cs#L68

The only difference I'm not using any IoC or singleton pattern, as it is initialized under `DocumentDbStorage` class. I don't think if the class is being re-initialized again 

Can you provide me an instance where it might re-initialized again

**Comment by dominikfoldi** [comment]
Yeah, you are initializing it only once. But if I use Cosmos DB in my project already for other storage related tasks I will have a DocumentClient already initialized. Then I would not want to initialize an another one for Hangfire, but use the already initialized one.

So maybe you should provide an extension method to initialize DocumentDbStorage with DocumentClient or without DocumentClient but use the already initialized one from the IoC.

E.g.:
https://github.com/codekoenig/AspNetCore.Identity.DocumentDb/blob/master/src/AspNetCore.Identity.DocumentDb/DocumentClientExtensions.cs

**Comment by imranmomin** [comment]
Sorry, I cannot use `IServiceCollection` or any IoC container as I don't want the user to be restricted to a  particular IoC library.

Also, the library targets .Net Framework.

**Comment by imranmomin** [comment]
@dominikfoldi  if you have any solution. Please create a pull-request and raise it against `Develop` branch

**Comment by dominikfoldi** [comment]
@imranmomin then maybe a version that is targets aspnet core would be a good solution. 

I don't have too much time right now to develop it, and this is not high prio, we will use SQL Server as an alternative.

Maybe in September I can come back to this.
