### ISSUE TITLE
Problem with manual trigger recuring job when using "Hangfire.Console" extension

### ISSUE THREAD

**Issue by karolzdunek** [imranmomin/Hangfire.AzureDocumentDB#30]
Hi. 
I am using AzureDocumentDb storage and Hangfire.Console in my project and I found possible issue.
I simply cannot run my scheduled job (recurring job) from the hangfire dashboard level [.../hangfire/recurring]

In browser debuging tools can see that there is unssaccesfull POST request (500 Internal error) 
.../hangfire/recurring/trigger
that returns following error:
### Unable to cast object of type 'Hangfire.Azure.DocumentDbWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.
When I just disable Hangfire.Console it works as expected
Please help:)
![image](https://user-images.githubusercontent.com/31654295/47717412-fbca6680-dc45-11e8-9246-435306919b0e.png)

**Comment by imranmomin** [comment]
@karolzdunek  I'm aware of the issue. I'm working on it. But no deadline.

**Comment by imranmomin** [comment]
@karolzdunek - I just released 3.0.0-beta with support to Hangfire.Console. Please try and let me know if any issues

**Comment by imranmomin** [comment]
released [3.0.0](https://github.com/imranmomin/Hangfire.AzureDocumentDB/releases/tag/3.0.0)
