### ISSUE TITLE
Serialization Issue When Polling Queue

### ISSUE THREAD

**Issue by amhenk** [imranmomin/Hangfire.AzureDocumentDB#39]
I came across a potential serialization issue within the DocumentBase.cs.

It seems that in the JobQueue.Deque Function the type SQLParameter gets serialized to a string but the created documents get an integer instead. This results in the query not finding any submitted jobs.

I have a fix using the NewtonSoft.Json.Converters.StringEnumConverter but maybe there's another way to solve this if it's not an issue for anyone else.

**Comment by imranmomin** [comment]
https://github.com/imranmomin/Hangfire.AzureDocumentDB/blob/e9ccc7cfeccc4de0eddcf0d56293f1a50349952f/Hangfire.AzureDocumentDB/Queue/JobQueue.cs#L36-L45

I don't think it should serialize to string as the SqlParameter takes object as value. Changing the serialization will affect other methods and queries. Can you try with - (int)Documents.DocumentTypes.Queue

```csharp
List<SqlParameter> parameters = new List<SqlParameter> { new SqlParameter("@type", (int)Documents.DocumentTypes.Queue) };
```

**Comment by amhenk** [comment]
Casting it as an int seems to allow the queue to work however the dashboard doesn't report anything. When I use the StringEnumConverter it seems to pick up the statuses and everything fine. Not sure if you're seeing something different on your

**Comment by imranmomin** [comment]
I have feeling somewhere in the default `JsonSerializerSettings` is getting override and it is converting enum to string

Is the document created in the db has the integer value or string

**Comment by amhenk** [comment]
That could be the case. In the `JsonConvert.DefaultSettings` we add it to the provided Converters. It seems that before I implemented the `StringEnumConverter` attribute the documents were getting ints for their enum values. However when we query with the enum to dequeue, it gets converted to a string.

Just so it's clear the change I made was: 
```C#
internal abstract class DocumentBase
{
     ...
     [JsonProperty("type")]
     [JsonConverter(typeof(StringEnumConverter))]
     public abstract DocumentTypes DocumentType { get; }
}
```

As for versions:
-  Hangfire.Core - 1.6.21
-  DocumentDB - 2.2.1
- Json.NET - 12.0.1

**Comment by imranmomin** [comment]
Can you remove the `StringEnumConverter`  from `JsonConvert.DefaultSettings` and `DocumentBase` and try

I think DocumentDB.Core does not considers the `JsonSerializerSettings` when using SqlQuerySpec

**Comment by amhenk** [comment]
Removing the `StringEnumConverter` from the default settings seemed to do the trick. I think I found a nice middle ground in my code that gets me the desired results without it there. Thank you for your help with this!

**Comment by imranmomin** [comment]
@amhenk anyway I will put a fix so that no one have to face this issue
