### ISSUE TITLE
Microsoft.Azure.DocumentDB.1.15.0 exception

### ISSUE THREAD

**Issue by dalestone** [imranmomin/Hangfire.AzureDocumentDB#4]
Hi, there seems to be an exception (missing method) being thrown when using 1.15.0 version, I had to downgrade to 1.14.0 to get it to work but would ideally prefer if it worked with 1.15.0.

On further investigation it looks like its actually related to Hangfire.AspNetCore 1.6.14 which falls over on
 o.UseAzureDocumentDbStorage()

**Comment by imranmomin** [comment]
@dalestone  - will fix for the final release.

**Comment by imranmomin** [comment]
@dalestone - today i released the newer version. Can you confirm if the issue is resolved.
