### ISSUE TITLE
Use of OFFSET/LIMIT not allowed for cross partition queries

### ISSUE THREAD

**Issue by graemechristie** [imranmomin/Hangfire.AzureDocumentDB#43]
I just pulled down and built the latest code from master. It's looks like there was a recent commit to move to using the new OFFSET/LIMIT functionality. 

https://github.com/imranmomin/Hangfire.AzureDocumentDB/commit/fada9da7781d5659171316ffc7f35a75ad8b110c#diff-cff4031e139919e9d61c1e27b1282150

OFFSET/LIMIT is not usable for cross partition queries (i.e. It is pretty much a useless feature ... ). As CosmosDB does not support non partitioned collections this change probably needs to be reverted.

**Comment by graemechristie** [comment]
Also looks like all a bunch of the Stored procs need to be refactored as they need partition keys specified... Is anyone running this lib against a Current CosmosDB Instance ? It looks to me as if a major part of the codebase needs to be refactored in order for this lib to be usable against the Current Azure offererings ...

**Comment by graemechristie** [comment]
It looks like if you partition your collection on the /type property ... the refactor becomes fairly simple. You don't need to modify your stored procs at all, you just need to pass the partition key (type) into all Stored proc executions. All of the of the current queries are descriminated by type, so this is fairly trivial. if you were to make this change however, you woudl break all existing users, at least those who had not partitioned their collections by type. Also - I imagine it is not a great partition key, as some document types (e.g. job) are going to have alot of documents and others not so much.

I have this running at the moment.

If you want me to put a PR up, I can possibly get one together this weekend. If the breaking change is not acceptable, maybe the option is to fork to a new project (Hangfire.AzureCosmosDb).

**Comment by imranmomin** [comment]
Regarding the change related to OFFSET/LIMIT my assumption was user won't have a partitioned collection. i.e user will have a seperate collection just for Hangfire.

I WAS WRONG. Lets fix it.

I was planning to start a new project under `Hangfire.AzureCosmosDb` and move to .NET 3.0 SDK. 
I can fork a new project and start making the change to match the offering

**Comment by graemechristie** [comment]
Yeah, I think that’s the right thing to do. Cosmos seems to have diverged significantly from the doc dB this lib was written for .. I’m happy to help.

**Comment by imranmomin** [comment]
Okay so I have imported the current repo in https://github.com/imranmomin/Hangfire.AzureCosmosDb
Also added you as collaborator. 

Let me know how you want to begin

**Comment by iyappanpugalendi** [comment]
> Okay so I have imported the current repo in https://github.com/imranmomin/Hangfire.AzureCosmosDb
> Also added you as collaborator.
> Let me know how you want to begin

Any timeline on providing support for partitioned collection? Thanks for your help.

**Comment by imranmomin** [comment]
@iyappanpugalendi - no plans yet. Looking for a collaborator to support me

**Comment by graemechristie** [comment]
Yes, sorry @iyappanpugalendi, that would probably be me. I've been a bit under the pump but I definitely want to get this kicked off. We probably need to have an initial design discussion about how we are going to structure the CosmosDb stuff, particularly around partition keys. I'm probably mostly available after 9pm in my timezone, which would be around 1pm-3pm GMT.

**Comment by imranmomin** [comment]
@graemechristie @iyappanpugalendi I have started porting the API. Once completed will ask you to apply the partition logic

**Comment by imranmomin** [comment]
Closing the issue here and create an issue on the AzureCosmosDB

https://github.com/imranmomin/Hangfire.AzureCosmosDb/issues/1
