### ISSUE TITLE
Hangfire Dashboard CamelCasing / PascalCase Issue

### ISSUE THREAD

**Issue by erikpaperik** [imranmomin/Hangfire.AzureDocumentDB#45]
I'm currently having a non deterministic behavior regarding the serialization of states.

My Hangfire setup code:
```cs
services.AddHangfire(configuration => configuration
        .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
        .UseSimpleAssemblyNameTypeSerializer()
        .UseAzureDocumentDbStorage(
              Configuration["Connections:Hangfire:URL"],
              Configuration["Connections:Hangfire:Secret"],
              Configuration["Connections:Hangfire:DBName"],
              Configuration["Connections:Hangfire:CollectionName"])
      );
```
When looking into the DocumentDB I have some documents using camel case
![image](https://user-images.githubusercontent.com/7869061/67551328-eaa52000-f708-11e9-88ae-4ac44d2f1239.png)
and other using pascal case
![image](https://user-images.githubusercontent.com/7869061/67551342-f4c71e80-f708-11e9-9993-a650258f268c.png)

Unitl now I didn't have the time to debug the entire code but I was able to produce consistent pascal cased values by initializing the serializer settings in `DocumentDbStorage` the following way:

```cs
JsonSerializerSettings settings = new JsonSerializerSettings
{
  NullValueHandling = NullValueHandling.Ignore,
  DateTimeZoneHandling = DateTimeZoneHandling.Utc,
  // Use other ContractResolver compared to current 3.0.2 package version
  // https://github.com/imranmomin/Hangfire.AzureDocumentDB/blob/develop/Hangfire.AzureDocumentDB/DocumentDbStorage.cs#L53
  ContractResolver = new DefaultContractResolver()
};
```

What I don't really get is that the current setting 
```cs
ContractResolver = new CamelCasePropertyNamesContractResolver
{
  NamingStrategy = new CamelCaseNamingStrategy(false, false)
}
```
returns a proper serialized object within a sample console application
```cs
Dictionary<string, string> values = new Dictionary<string, string>
{
  { "EnqueuedAt", "Value1!" },
  { "Queue", "Value2!" }
};

// Returns
//{
//  "EnqueuedAt": "Value1!",
//  "Queue": "Value2!"
//}
```

As soon as we have this camel cased values in our documents the Hangfire Dashboard throws exceptions since the `DocumentDbMonitoringApi` uses pascal cased literals to access state data.

Do you have any ideas on this where to start?

Best
Erik

**Comment by imranmomin** [comment]
@erikpaperik it weird that the dictionary are saved differently. 

Can you check `DocumentDbWriteOnlyTransaction` for the below methods which saves the data. 

- `AddJobState`
- `SetJobState` - I have doubt on this method as it uses the stored procedure and I know there is was a bug, where the execute method does not considers the json settings.

**Comment by imranmomin** [comment]
@erikpaperik I have fix for the issue. Can you pull down the branch and test 

https://github.com/imranmomin/Hangfire.AzureDocumentDB/tree/bug-fixes

**Comment by erikpaperik** [comment]
@imranmomin I'll test it today!
Thank you very much!

**Comment by erikpaperik** [comment]
@imranmomin 
There is a small piece we have to change in the `camelCaseToPascalCase` method.
https://github.com/imranmomin/Hangfire.AzureDocumentDB/commit/11d7726cd278573240905aa80c2958495fa26469#r35690713

**Comment by imranmomin** [comment]
Fixed and released under v3.0.3

**Comment by erikpaperik** [comment]
Hey @imranmomin 

we're using the latest version of this package and discovered this error again - but now it's only appearing in failed jobs:

![image](https://user-images.githubusercontent.com/7869061/68388328-a9792b00-0160-11ea-9e18-fc5b095f9aa0.png)

All other states (Enqueued, Processing, ..) are working fine.

Is there an other handling or call to update the job state for failed jobs apart from this `setJobState` in setJobState.ts ?https://github.com/imranmomin/Hangfire.AzureDocumentDB/blob/7d6b01c54d1414154900d5f71228c101f1b27e32/Hangfire.AzureDocumentDB/StoredProcedure/setJobState.ts#L6
Sorry for not discovering this problem the last time we investigated in this camelCase / Pascal Case issue :-/

**Comment by imranmomin** [comment]
The only other place is at 

https://github.com/imranmomin/Hangfire.AzureDocumentDB/blob/7d6b01c54d1414154900d5f71228c101f1b27e32/Hangfire.AzureDocumentDB/DocumentDbWriteOnlyTransaction.cs#L175-L194

Can you forcefully fail a job and debug what it save. Also compare the data with other state
To be sure can you also place a debugger on https://github.com/imranmomin/Hangfire.AzureDocumentDB/blob/7d6b01c54d1414154900d5f71228c101f1b27e32/Hangfire.AzureDocumentDB/DocumentDbWriteOnlyTransaction.cs#L153

Sorry, that we are still facing the serialization issue

**Comment by erikpaperik** [comment]
Within the `AddJobState` the expression `state.SerializeData()` yields the correctly serialized data:
![image](https://user-images.githubusercontent.com/7869061/68570177-4dfcb500-0460-11ea-83d3-9a6e30ed8571.png)

Having a look into the DocumentDB reveals camel case serialzied keys:
![image](https://user-images.githubusercontent.com/7869061/68570240-708ece00-0460-11ea-9dc5-65e01e982db8.png)

I can provide you a minimal sample application to reproduce the issue:
https://github.com/erikpaperik/hangfire_casing_bug

I guess the serialization problem is somehow linked to the `Elastic.Apm*` package we use in each and every api of our system (also included in the sample app). 
Without the app instrumentation `app.UseAllElasticApm(Configuration);` it always serializes the data in the correct format.
The included README-File contains all steps to reproduce this issue.

**Comment by imranmomin** [comment]
Wired that its happening only for Failed exceptions.

**Comment by imranmomin** [comment]
@erikpaperik - I think i fixed the issue. Can you test the fix at your end.

![image](https://user-images.githubusercontent.com/6071075/68676725-997a9600-0528-11ea-83a3-09228dcdcbf9.png)

Can you pull the branch and give a try - https://github.com/imranmomin/Hangfire.AzureDocumentDB/tree/camel-case-fix

**Comment by imranmomin** [comment]
@erikpaperik we you able to test

**Comment by erikpaperik** [comment]
@imranmomin 
Sorry for the delay. I'll try to test this fix during this week - currently pretty busy times at work 😕
Thanks in advance for your work and patience! 👍

**Comment by erikpaperik** [comment]
@imranmomin 
I was able to test the fix successfully!
Thank you very much!

**Comment by imranmomin** [comment]
Prefect.. will soon push the release
