### ISSUE TITLE
Getting migration issue when using azure cosmos db with hangfire

### ISSUE THREAD

**Issue by schandra09net** [imranmomin/Hangfire.AzureDocumentDB#51]
var migrationOptions = new MongoMigrationOptions
            {
                Strategy = MongoMigrationStrategy.Migrate,
                BackupStrategy = MongoBackupStrategy.Collections
            };
            var storageOptions = new MongoStorageOptions
            {
                MigrationOptions = migrationOptions,
                ConnectionCheckTimeout = TimeSpan.FromSeconds(100),
                MigrationLockTimeout=TimeSpan.FromSeconds(100)
            };            
// Azure cosomos db connection string GlobalConfiguration.Configuration.UseMongoStorage("mongodb://username:password@azure_url/?ssl=true&sslAllowInvalidCertificates=true", "ApplicationDatabase", storageOptions);

**Error:**
could not complete migration. Never acquired lock within allowed time: 00:01:00
Either another server did not complete the migration or migration was abruptly interrupted"

Just in case, if the above config is wrong, how to get the auth token below ( i have username and password from azure cosmos DB connections strings)
  var storageOptions = new DocumentDbStorageOptions
            {                
                ConnectionProtocol=Protocol.Https,
            };
            GlobalConfiguration.Configuration.UseAzureDocumentDbStorage("azuredburl", "what is this??", "ApplicationDatabase", "collectionname in cosmos db", storageOptions);

please let me know

**Comment by imranmomin** [comment]
U need to pass the primary key i.e authSecret

![image](https://user-images.githubusercontent.com/6071075/76089713-348bf580-5f88-11ea-9877-b75596c26eef.png)
