### ISSUE TITLE
Does new updates support custom partition key?

### ISSUE THREAD

**Issue by vtatarinsw** [imranmomin/Hangfire.AzureDocumentDB#54]
Hello,

  I started use your nuget inside our project, but as we were need to have partition key support I updated the code to support it. For example, we use "/pKey" partition path name in our solution.

  I would make a a fork and commit my updates there, but found that you already move forward and add new code to support partitions.
  Does it work with any paritition name I can setup? Any limits?

Thanks,
Volodymyr

**Comment by imranmomin** [comment]
@vtatarinsw - right now the partition cannot be custom and is defaulted to /type

**Comment by vtatarinsw** [comment]
@imranmomin Clear, thanks! I will try to merge the latest from your code and my updates to having custom partitions. But will need to test. Current implementation works fine on our development server. I will let you know when it's available in the fork. 

Thanks!
P.S. You did Great Job about all these packages!
