### ISSUE TITLE
Error on initialize storage - System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by penihel** [imranmomin/Hangfire.AzureDocumentDB#55]
![image](https://user-images.githubusercontent.com/1167747/80136641-6547de80-8578-11ea-9591-53eb9b039083.png)

GlobalConfiguration.Configuration.UseAzureDocumentDbStorage

This happen sometimes, my credential are ok

**Comment by imranmomin** [comment]
@penihel  - well from the screenshot it looks like a task cancelled exception. This may be due to may reason

Can you check the logs or can u provide me with more information
