### ISSUE TITLE
"PartitionKey extracted from document doesn't match the one specified in the header"

### ISSUE THREAD

**Issue by vinayramegowda** [imranmomin/Hangfire.AzureDocumentDB#60]
I have a CosmosDB with partition key set to "/id" and I wanted to know if there is any way I could change the partition key value from "/type" (by default) to "/id" in the options provided in `DocumentDbStorageOptions` or anywhere. Any help would be appreciated.

Cheers,
Vinay

**Comment by imranmomin** [comment]
@vinayramegowda  - Sorry, you will not able to change the default partition key. Only option for you is to fork the repo out and make the changes OR you can create a separate collection/database for hangfire
